#QuickPlant Configuration
#Damp Configuration
#Activate creeper dampness
creeper_dampness = true
#Activate TNT dampness
tnt_dampness = true
#What's the max fuse time when the creeper reaches his max dampness
#Range: > 100
creeper_swell = 2000
#What's the max fuse time when the primed tnt reaches his max dampness
#Range: > 100
tnt_fuse = 2000
